# Generated by Django 2.2.6 on 2019-10-04 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=20)),
                ('goal_id', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
                ('moved_by', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrummaster.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrummaster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumHistroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
                ('moved_from', models.CharField(max_length=20)),
                ('moved_to', models.CharField(max_length=20)),
                ('time_of_action', models.DateTimeField(max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrummaster.ScrumyGoals')),
            ],
        ),
    ]
